# permissions for end users to view solacescalables.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: solacescalable-viewer-role
rules:
- apiGroups:
  - scalable.solace.io
  resources:
  - solacescalables
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scalable.solace.io
  resources:
  - solacescalables/status
  verbs:
  - get
